#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileDocumentBackupAndDelete.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="S3Uploader")]
	public partial class S3UploaderDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public S3UploaderDataContext() : 
				base(global::SmileDocumentBackupAndDelete.Properties.Settings.Default.S3UploaderConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public S3UploaderDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public S3UploaderDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public S3UploaderDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public S3UploaderDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_UploaderConfig_Select")]
		public ISingleResult<usp_UploaderConfig_SelectResult> usp_UploaderConfig_Select([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParameterName", DbType="NVarChar(MAX)")] string parameterName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), parameterName);
			return ((ISingleResult<usp_UploaderConfig_SelectResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_DocumentFileDelete_Update")]
		public ISingleResult<usp_DocumentFileDelete_UpdateResult> usp_DocumentFileDelete_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Code", DbType="VarChar(20)")] string code)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), code);
			return ((ISingleResult<usp_DocumentFileDelete_UpdateResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_Uploader_Log_Insert")]
		public ISingleResult<usp_Uploader_Log_InsertResult> usp_Uploader_Log_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Document_ID", DbType="VarChar(20)")] string document_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FILENAME", DbType="NVarChar(MAX)")] string fILENAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorMessage", DbType="NVarChar(MAX)")] string errorMessage, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DocType", DbType="NVarChar(MAX)")] string docType)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), document_ID, fILENAME, errorMessage, docType);
			return ((ISingleResult<usp_Uploader_Log_InsertResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_DocumentFilelistS3_Update")]
		public ISingleResult<usp_DocumentFilelistS3_UpdateResult> usp_DocumentFilelistS3_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Code", DbType="VarChar(20)")] string code, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="S3IsUploaded", DbType="Bit")] System.Nullable<bool> s3IsUploaded, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="S3Bucket", DbType="VarChar(255)")] string s3Bucket, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="S3StorageType", DbType="VarChar(255)")] string s3StorageType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="S3Key", DbType="VarChar(MAX)")] string s3Key)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), code, s3IsUploaded, s3Bucket, s3StorageType, s3Key);
			return ((ISingleResult<usp_DocumentFilelistS3_UpdateResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_DocumentFileDelete_Select")]
		public ISingleResult<usp_DocumentFileDelete_SelectResult> usp_DocumentFileDelete_Select()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<usp_DocumentFileDelete_SelectResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_SmileDoclistS3_Update", IsComposable=true)]
		public object usp_SmileDoclistS3_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AttachmentID", DbType="VarChar(20)")] string attachmentID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="S3IsUploaded", DbType="Bit")] System.Nullable<bool> s3IsUploaded, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="S3Bucket", DbType="VarChar(255)")] string s3Bucket, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="S3StorageType", DbType="VarChar(255)")] string s3StorageType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="S3Key", DbType="VarChar(MAX)")] string s3Key)
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), attachmentID, s3IsUploaded, s3Bucket, s3StorageType, s3Key).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_SmileDoclistDelete_Update")]
		public ISingleResult<usp_SmileDoclistDelete_UpdateResult> usp_SmileDoclistDelete_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AttachmentID", DbType="VarChar(20)")] string attachmentID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="S3IsUploaded", DbType="Bit")] System.Nullable<bool> s3IsUploaded, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="S3Bucket", DbType="VarChar(255)")] string s3Bucket, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="S3StorageType", DbType="VarChar(255)")] string s3StorageType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="S3Key", DbType="VarChar(MAX)")] string s3Key)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), attachmentID, s3IsUploaded, s3Bucket, s3StorageType, s3Key);
			return ((ISingleResult<usp_SmileDoclistDelete_UpdateResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_SmileDoclistDelete_Select")]
		public ISingleResult<usp_SmileDoclistDelete_SelectResult> usp_SmileDoclistDelete_Select()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<usp_SmileDoclistDelete_SelectResult>)(result.ReturnValue));
		}
	}
	
	public partial class usp_UploaderConfig_SelectResult
	{
		
		private string _ParameterName;
		
		private System.Nullable<double> _ValueNumber;
		
		private string _ValueString;
		
		private System.Nullable<System.DateTime> _ValueDateTime;
		
		private System.Nullable<bool> _ValueBoolean;
		
		private string _Remark;
		
		public usp_UploaderConfig_SelectResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParameterName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ParameterName
		{
			get
			{
				return this._ParameterName;
			}
			set
			{
				if ((this._ParameterName != value))
				{
					this._ParameterName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValueNumber", DbType="Float")]
		public System.Nullable<double> ValueNumber
		{
			get
			{
				return this._ValueNumber;
			}
			set
			{
				if ((this._ValueNumber != value))
				{
					this._ValueNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValueString", DbType="NVarChar(255)")]
		public string ValueString
		{
			get
			{
				return this._ValueString;
			}
			set
			{
				if ((this._ValueString != value))
				{
					this._ValueString = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValueDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> ValueDateTime
		{
			get
			{
				return this._ValueDateTime;
			}
			set
			{
				if ((this._ValueDateTime != value))
				{
					this._ValueDateTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValueBoolean", DbType="Bit")]
		public System.Nullable<bool> ValueBoolean
		{
			get
			{
				return this._ValueBoolean;
			}
			set
			{
				if ((this._ValueBoolean != value))
				{
					this._ValueBoolean = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="NVarChar(MAX)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this._Remark = value;
				}
			}
		}
	}
	
	public partial class usp_DocumentFileDelete_UpdateResult
	{
		
		private System.Nullable<bool> _Result;
		
		public usp_DocumentFileDelete_UpdateResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="Bit")]
		public System.Nullable<bool> Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this._Result = value;
				}
			}
		}
	}
	
	public partial class usp_Uploader_Log_InsertResult
	{
		
		private System.Nullable<bool> _Result;
		
		public usp_Uploader_Log_InsertResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="Bit")]
		public System.Nullable<bool> Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this._Result = value;
				}
			}
		}
	}
	
	public partial class usp_DocumentFilelistS3_UpdateResult
	{
		
		private System.Nullable<bool> _Result;
		
		public usp_DocumentFilelistS3_UpdateResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="Bit")]
		public System.Nullable<bool> Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this._Result = value;
				}
			}
		}
	}
	
	public partial class usp_DocumentFileDelete_SelectResult
	{
		
		private string _Code;
		
		private string _FileName;
		
		private string _PhysicalPath;
		
		private string _S3Key;
		
		private string _S3StorageType;
		
		private System.Nullable<System.DateTime> _S3StorageTypeUpdateDate;
		
		private System.Nullable<System.DateTime> _S3UploadedDate;
		
		private string _S3Bucket;
		
		public usp_DocumentFileDelete_SelectResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="NVarChar(MAX)")]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this._FileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhysicalPath", DbType="NVarChar(MAX)")]
		public string PhysicalPath
		{
			get
			{
				return this._PhysicalPath;
			}
			set
			{
				if ((this._PhysicalPath != value))
				{
					this._PhysicalPath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S3Key", DbType="VarChar(MAX)")]
		public string S3Key
		{
			get
			{
				return this._S3Key;
			}
			set
			{
				if ((this._S3Key != value))
				{
					this._S3Key = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S3StorageType", DbType="VarChar(255)")]
		public string S3StorageType
		{
			get
			{
				return this._S3StorageType;
			}
			set
			{
				if ((this._S3StorageType != value))
				{
					this._S3StorageType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S3StorageTypeUpdateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> S3StorageTypeUpdateDate
		{
			get
			{
				return this._S3StorageTypeUpdateDate;
			}
			set
			{
				if ((this._S3StorageTypeUpdateDate != value))
				{
					this._S3StorageTypeUpdateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S3UploadedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> S3UploadedDate
		{
			get
			{
				return this._S3UploadedDate;
			}
			set
			{
				if ((this._S3UploadedDate != value))
				{
					this._S3UploadedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S3Bucket", DbType="VarChar(255)")]
		public string S3Bucket
		{
			get
			{
				return this._S3Bucket;
			}
			set
			{
				if ((this._S3Bucket != value))
				{
					this._S3Bucket = value;
				}
			}
		}
	}
	
	public partial class usp_SmileDoclistDelete_UpdateResult
	{
		
		private System.Nullable<bool> _Result;
		
		public usp_SmileDoclistDelete_UpdateResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="Bit")]
		public System.Nullable<bool> Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this._Result = value;
				}
			}
		}
	}
	
	public partial class usp_SmileDoclistDelete_SelectResult
	{
		
		private System.Nullable<int> _AttachmentID;
		
		private string _FileName;
		
		private string _PhysicalPath;
		
		private string _S3Key;
		
		private string _S3StorageType;
		
		private System.Nullable<System.DateTime> _S3StorageTypeUpdateDate;
		
		private System.Nullable<System.DateTime> _S3UploadedDate;
		
		private string _S3Bucket;
		
		public usp_SmileDoclistDelete_SelectResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttachmentID", DbType="Int")]
		public System.Nullable<int> AttachmentID
		{
			get
			{
				return this._AttachmentID;
			}
			set
			{
				if ((this._AttachmentID != value))
				{
					this._AttachmentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="NVarChar(255)")]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this._FileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhysicalPath", DbType="NVarChar(MAX)")]
		public string PhysicalPath
		{
			get
			{
				return this._PhysicalPath;
			}
			set
			{
				if ((this._PhysicalPath != value))
				{
					this._PhysicalPath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S3Key", DbType="VarChar(255)")]
		public string S3Key
		{
			get
			{
				return this._S3Key;
			}
			set
			{
				if ((this._S3Key != value))
				{
					this._S3Key = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S3StorageType", DbType="VarChar(255)")]
		public string S3StorageType
		{
			get
			{
				return this._S3StorageType;
			}
			set
			{
				if ((this._S3StorageType != value))
				{
					this._S3StorageType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S3StorageTypeUpdateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> S3StorageTypeUpdateDate
		{
			get
			{
				return this._S3StorageTypeUpdateDate;
			}
			set
			{
				if ((this._S3StorageTypeUpdateDate != value))
				{
					this._S3StorageTypeUpdateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S3UploadedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> S3UploadedDate
		{
			get
			{
				return this._S3UploadedDate;
			}
			set
			{
				if ((this._S3UploadedDate != value))
				{
					this._S3UploadedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S3Bucket", DbType="VarChar(255)")]
		public string S3Bucket
		{
			get
			{
				return this._S3Bucket;
			}
			set
			{
				if ((this._S3Bucket != value))
				{
					this._S3Bucket = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
