//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmilesUploadToS3.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.100.50;Initial Catalog=S3Uploader;Persist Security Info=True;" +
            "User ID=devdba;Password=-v200wfhxt;MultipleActiveResultSets=True")]
        public string S3UploaderConnectionString {
            get {
                return ((string)(this["S3UploaderConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.100.50;Initial Catalog=S3Uploader;Persist Security Info=True;" +
            "User ID=devdba;Password=-v200wfhxt")]
        public string S3UploaderConnectionString1 {
            get {
                return ((string)(this["S3UploaderConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=27.254.238.180;Initial Catalog=S3Uploader;Persist Security Info=True;" +
            "User ID=devcrud;Password=Fi\'giupo-v\'gikojkvp^j;MultipleActiveResultSets=True;Con" +
            "nect Timeout=10")]
        public string DBSSSDoc {
            get {
                return ((string)(this["DBSSSDoc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=147.50.133.148;Initial Catalog=S3Uploader;Persist Security Info=True;" +
            "User ID=sa;Password=Fi\'giupo-v\'gikojkvp^j;MultipleActiveResultSets=True;Connect " +
            "Timeout=10")]
        public string DBSmileDoc {
            get {
                return ((string)(this["DBSmileDoc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=147.50.133.169;Initial Catalog=S3Uploader;Persist Security Info=True;" +
            "User ID=devdba;Password=-v200wfhxt;MultipleActiveResultSets=True;Connect Timeout" +
            "=10")]
        public string DBTest {
            get {
                return ((string)(this["DBTest"]));
            }
        }
    }
}
