//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmilesUploadToS3.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class S3UploaderDataContext : DbContext
    {
        public S3UploaderDataContext()
            : base("name=S3UploaderDataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<usp_DocumentFilelist_Select_Result> usp_DocumentFilelist_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_DocumentFilelist_Select_Result>("usp_DocumentFilelist_Select");
        }
    
        public virtual ObjectResult<usp_UploaderConfig_Select_Result> usp_UploaderConfig_Select(string parameterName)
        {
            var parameterNameParameter = parameterName != null ?
                new ObjectParameter("ParameterName", parameterName) :
                new ObjectParameter("ParameterName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_UploaderConfig_Select_Result>("usp_UploaderConfig_Select", parameterNameParameter);
        }
    }
}
