//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmilesUploadToS3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploaderConfig
    {
        public string ParameterName { get; set; }
        public Nullable<double> ValueNumber { get; set; }
        public string ValueString { get; set; }
        public Nullable<System.DateTime> ValueDateTime { get; set; }
        public Nullable<bool> ValueBoolean { get; set; }
        public string Remark { get; set; }
    }
}
